# Use R
language: r
cache: packages
warnings_are_errors: false

r: release
os: linux

addons:
  apt:
    packages:
      - terra-dev
      - raster-dev
      - leaflet-dev

notifications:
  email:
    on_success: change
    on_failure: change
