# Use R
language: r
sudo: true
cache: packages
warnings_are_errors: false

r: release
os: osx

before_install:
  - sudo apt-get install ggiraph

notifications:
  email:
    on_success: change
    on_failure: change
