# Use R
language: r
cache: packages
warnings_are_errors: false

r: release
os: osx

before_install:
  - sudo apt-get -y install terra-dev
  - sudo apt-get -y install raster-dev
  - sudo apt-get -y install leaflet-dev

notifications:
  email:
    on_success: change
    on_failure: change
