# Use R
language: r
cache: packages
warnings_are_errors: false

r: release
os: linux

before_install:
  - sudo apt-get -y install terra
  - sudo apt-get -y install raster
  - sudo apt-get -y install leaflet

notifications:
  email:
    on_success: change
    on_failure: change
